#!/bin/sh

echo "╔════════════════════════════════════════════════╗"
echo "║              Running pre-push hook             ║"
echo "╚════════════════════════════════════════════════╝"

set -e

# golangci-lint run || (echo "ERROR Lint failed" && exit 1)
make build || (echo "ERROR Build failed" && exit 1)
